line-length = 120
show-fixes = true

[analyze]
detect-string-imports = true

[format]
docstring-code-format = true
skip-magic-trailing-comma = true

[lint]
future-annotations = true
select = [
    "E",   # pycodestyle
    "F",   # Pyflakes
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "SIM", # flake8-simplify
    "I",   # isort
    "ANN", # flake8-annotations
]

[lint.isort]
split-on-trailing-comma = false # incompatible with format.skip-magic-trailing-comma
